name: Deploy Hugo Site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs when repository_dispatch event is triggered
  repository_dispatch:
    types: [deploy]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0

    steps:
      - name: Checkout Hugo site repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Debug - List contents of Hugo site repo
        run: ls -R .

      - name: Checkout remote vault repo
        uses: actions/checkout@v4
        with:
          repository: nicolemah99/obsidian
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: obsidian-vault
          fetch-depth: 1

      - name: Debug - List contents of obsidian-vault
        run: ls -R ./obsidian-vault

      - name: Debug - List contents of content before copy
        run: ls -R ./obsiditan-site

      - name: Sync Obsidian content to Hugo site
        run: |
          rm -rf ./content/*
          cp -r ./obsidian-vault/* ./content/

      - name: Debug - List contents of content after copy
        run: ls -R ./content

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: America/Los_Angeles
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build-and-deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
